name: local_mart
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.


dependencies:
  flutter:

    sdk: flutter

  google_fonts: ^6.1.0
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  google_sign_in: ^6.1.0
  flutter_facebook_auth: ^6.1.2
  cloud_firestore: ^6.0.3
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  http: ^1.2.2
  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  geolocator: ^14.0.2
  intl: ^0.20.2
  firebase_messaging: ^16.0.3
  flutter_local_notifications: ^18.0.1
  uuid: ^4.4.0
  device_calendar: ^4.3.0
  permission_handler: ^11.3.0
  timezone: ^0.9.2
  razorpay_flutter: ^1.3.7
  flutter_lints: ^6.0.0
  flutter_dotenv: ^6.0.0
  emailjs: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env
  fonts:
    - family: IndieFlower
      fonts:
        - asset: fonts/IndieFlower-Regular.ttf
dev_dependencies:
  flutter_test:
    sdk: flutter

