name: projects
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.1.0
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  google_sign_in: ^6.1.0
  flutter_facebook_auth: ^6.1.2
  cloud_firestore: ^6.0.3
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  http: ^1.2.2
  flutter_dotenv: ^5.0.2
  cupertino_icons: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0



flutter:
  uses-material-design: true

  assets:
    - assets/
    - .env
  fonts:
    - family: IndieFlower
      fonts:
        - asset: fonts/IndieFlower-Regular.ttf
